# Generated by Django 2.0 on 2017-12-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80, verbose_name='Usuário')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('lotacao', models.CharField(max_length=15, verbose_name='Lotação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Logs de operações',
                'verbose_name': 'Log de operação',
            },
        ),
        migrations.CreateModel(
            name='SendMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80, verbose_name='Usuário')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('lotacao', models.CharField(max_length=15, verbose_name='Lotação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('titulo_mensagem', models.CharField(max_length=30, verbose_name='Título da Mensagem')),
                ('conteudo_mensagem', models.CharField(max_length=210, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name_plural': 'Históricos de Mensagens',
                'verbose_name': 'Histórico de Mensagens',
            },
        ),
        migrations.CreateModel(
            name='UsuariosAutorizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=80, verbose_name='Usuário')),
                ('lotacao', models.CharField(max_length=15, verbose_name='Lotação')),
                ('adicionado_por', models.CharField(max_length=15, verbose_name='Adicionado por')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name_plural': 'Usuários autorizados',
                'verbose_name': 'Usuário autorizado',
            },
        ),
    ]
