# Generated by Django 2.0 on 2017-12-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmessagehistory',
            options={'permissions': (('send_message', 'Pode enviar mensagens'),), 'verbose_name': 'Histórico de Mensagens', 'verbose_name_plural': 'Históricos de Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='usuariosautorizados',
            options={'permissions': (('edit_permissions', 'Pode adicionar/remover usuários autorizados'),), 'verbose_name': 'Usuário autorizado', 'verbose_name_plural': 'Usuários autorizados'},
        ),
    ]
