# Generated by Django 2.0 on 2017-12-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171227_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosautorizados',
            options={'permissions': (('edit_authorized', 'Pode adicionar/remover usuários autorizados'),), 'verbose_name': 'Usuário autorizado', 'verbose_name_plural': 'Usuários autorizados'},
        ),
    ]
